global:
  namespace: quick-haul
  replicaCount: 2
  nodePort: 30080
  nfsServer: "172.31.31.186"
  nfsPath: "/mnt/nfs/mongodb"
  
  images:
    auth: "sathvik2003/quickhaul-auth:v3"
    booking: "sathvik2003/quickhaul-booking:v4"
    location: "sathvik2003/quickhaul-location:v5"
    notification: "sathvik2003/quickhaul-notification:v3"
    otp: "sathvik2003/quickhaul-otp:v3"
    frontend: "sathvik2003/quickhaul-frontend:v8"
    mongodb: "mongo:latest"
    redis: "redis:latest"

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
