apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
    app: {{ include "notification-service.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "notification-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "notification-service.name" . }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ include "notification-service.name" . }}
              topologyKey: "kubernetes.io/hostname"
      
      initContainers:
      - name: wait-for-mongodb
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mongodb.{{ .Release.Namespace }}.svc.cluster.local; do echo waiting for mongodb; sleep 2; done"]

      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["uvicorn", "services.notification_service.app:app", "--host", "0.0.0.0", "--port", "{{ .Values.service.port }}"]
        ports:
        - containerPort: {{ .Values.service.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.config.configMapName }}
        - secretRef:
            name: {{ .Values.config.secretName }}
