apiVersion: v1
kind: Secret
metadata:
  name: quick-haul-secrets
  namespace: quick-haul
type: Opaque
stringData:
  SECRET_KEY: "hello_welcome_to_quick_haul_transports"
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "password123"
  SMTP_PASSWORD: "qgao dqvk jiut ktyhr"

