apiVersion: v1
kind: Service
metadata:
  name: {{ include "otp-service.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "otp-service.name" . }}
