replicaCount: 2

image:
  repository: sathvik2003/quickhaul-auth
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8002

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

probes:
  liveness:
    path: /
    initialDelaySeconds: 30
  readiness:
    path: /
    initialDelaySeconds: 10

# These link to your global ConfigMap/Secret names
config:
  configMapName: quick-haul-config
  secretName: quick-haul-secrets
