apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-service
  namespace: quick-haul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otp-service
  template:
    metadata:
      labels:
        app: otp-service
    spec:
      containers:
      - name: otp-service
        image: sathvik2003/quickhaul-otp:v1`n        command: ["uvicorn", "services.otp_service.app:app", "--host", "0.0.0.0", "--port", "8005"]
        ports:
        - containerPort: 8005
        envFrom:
        - configMapRef:
            name: quick-haul-config
        - secretRef:
            name: quick-haul-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: otp-service
  namespace: quick-haul
spec:
  type: ClusterIP
  ports:
  - port: 8005
    targetPort: 8005
  selector:
    app: otp-service



