apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs/mongodb
    server: <NFS_SERVER_IP> # Replace with your EC2 Private IP
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-nfs-pvc
  namespace: quick-haul
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: mongodb-nfs-pv
  storageClassName: "" # Use "" to match the manual PV
