apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: quick-haul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: sathvik2003/quickhaul-booking:v1`n        command: ["uvicorn", "services.booking_service.app:app", "--host", "0.0.0.0", "--port", "8003"]
        ports:
        - containerPort: 8003
        envFrom:
        - configMapRef:
            name: quick-haul-config
        - secretRef:
            name: quick-haul-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: quick-haul
spec:
  type: ClusterIP
  ports:
  - port: 8003
    targetPort: 8003
  selector:
    app: booking-service



