replicaCount: 2

image:
  repository: sathvik2003/quickhaul-frontend
  tag: v3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

probes:
  liveness:
    path: /
    initialDelaySeconds: 30
  readiness:
    path: /
    initialDelaySeconds: 10

config:
  configMapName: quick-haul-config
  secretName: quick-haul-secrets
