apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: quick-haul
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: quick-haul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.global.images.mongodb }}
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        envFrom:
        - secretRef:
            name: quick-haul-secrets
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-nfs-pvc

