apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: quickhaul-gateway
  namespace: quick-haul
spec:
  gatewayClassName: eg
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-gateway-nodeport
  namespace: envoy-gateway-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 10080
    nodePort: 30080
  selector:
    gateway.envoyproxy.io/owning-gateway-namespace: quick-haul
    gateway.envoyproxy.io/owning-gateway-name: quickhaul-gateway
